// Code generated by kanban/gen. DO NOT EDIT.

package banner

// Zerobot Feng Edition 版本
var Version = "v2.4.1 (d012b4c)"

// Zerobot-Plugin 官方版本
var OriginalVersion = "v1.10.1 (0142050)"

// 依赖 zbputils Feng Edition 版本
var UtilsVersion = "v1.8.0 (d503137)"

// 依赖 zbputils 官方版本
var OriginalUtilsVersion = "v1.7.1 (058e1af)"

// 依赖 AnimeAPI Feng Edition 版本
var ApiVersion = "v1.8.6 (53ec086)"

// 依赖 AnimeAPI 官方版本
var OriginalApiVersion = "v1.7.0 (0c948e3)"

// Copyright
var Copyright = "© 2020 - 2025 FloatTech | © 2023 - 2025 QingFeng"

// 发送 /help 命令显示的版权信息
var Banner = "Zerobot " + Version + " Feng Edition, based on ZeroBotPlugin " + OriginalVersion + ".\n" +
	"Using zbputils " + UtilsVersion + " Feng Edition, based on zbputils " + OriginalUtilsVersion + ".\n" +
	"Using AnimeAPI " + ApiVersion + " Feng Edition, based on AnimeAPI " + OriginalApiVersion + ".\n" +
	"Copyright " + Copyright + ". All Rights Reserved.\n"
