// Code generated by kanban/gen. DO NOT EDIT.

package banner

// Version ...
var Version = "v1.9.9 (e6a4dfc)"

// Copyright ...
var Copyright = "© 2020 - 2025 FloatTech"

// Banner ...
var Banner = "Zerobot " + Version + " Feng Edition.\n" +
    "Copyright " + Copyright + ". All Rights Reserved.\n"