// Code generated by kanban/gen. DO NOT EDIT.

package banner

// Version ...
var Version = "v2.4.0-alpha.11 (2f1a8af)"
var OriginalVersion = "v1.9.9 (e6a4dfc)"
var zbputilsVersion = "v1.7.10 (8b76b32)"
var originalZbputilsVersion = "v1.7.2 (2741050)"

// Copyright ...
var Copyright = "© 2020 - 2025 FloatTech"

// Banner ...
var Banner = "Zerobot " + Version + " Feng Edition, based on ZeroBotPlugin " + OriginalVersion + ".\n" +
		"Using zbputils " + zbputilsVersion + " Feng Edition, based on zbputils " + originalZbputilsVersion + ".\n" +
    "Copyright " + Copyright + ". All Rights Reserved.\n"